services:

  # Graylog database MongoDB  
  graylog-mongodb:
    image: "mongo:5.0"
    networks:
      project_net:
        ipv4_address: 172.20.10.60
    volumes:
      - "mongodb_data:/data/db"
    restart: "unless-stopped"

  # Graylog datanode
  graylog-datanode:
    hostname: "datanode"
    image: "${DATANODE_IMAGE:-graylog/graylog-datanode:6.1}"
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      GRAYLOG_DATANODE_PASSWORD_SECRET: "supertajnehaslo1234"
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: "47d32aebc586c0d39786363393d9d2d964173e91c742edb0d86d400cf6861314"
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://graylog-mongodb:27017/graylog"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      project_net:
        ipv4_address: 172.20.10.61
    ports:
      - "8999:8999/tcp"   # DataNode API
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    volumes:
      - "graylog_datanode:/var/lib/graylog-datanode"
    restart: "unless-stopped"

  # Graylog server
  graylog-server:
    hostname: "server"
    image: "${GRAYLOG_IMAGE:-graylog/graylog:6.1}"
    depends_on:
      graylog-mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      GRAYLOG_PASSWORD_SECRET: "supertajnehaslo1234"
      GRAYLOG_ROOT_PASSWORD_SHA2: "47d32aebc586c0d39786363393d9d2d964173e91c742edb0d86d400cf6861314"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://graylog-mongodb:27017/graylog"
    networks:
      project_net:
        ipv4_address: 172.20.10.62
    ports:
    - "5044:5044/tcp"   # Beats
    - "5140:5140/udp"   # Syslog
    - "5140:5140/tcp"   # Syslog
    - "5555:5555/tcp"   # RAW TCP
    - "5555:5555/udp"   # RAW UDP
    - "9000:9000/tcp"   # Server API
    - "12201:12201/tcp" # GELF TCP
    - "12201:12201/udp" # GELF UDP
    #- "10000:10000/tcp" # Custom TCP port
    #- "10000:10000/udp" # Custom UDP port
    - "13301:13301/tcp" # Forwarder data
    - "13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    restart: "unless-stopped"    
      
networks:
  project_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.10.0/24
          gateway: 172.20.10.254
          #aux_addresses:
            #zabbix_mysql: 172.20.10.50
            #zabbix_server: 172.20.10.51
            #zabbix_nginx: 172.20.10.52
            #graylog_mongodb: 172.20.10.60
            #graylog_datanode: 172.20.10.61
            #graylog_server: 172.20.10.62
            #grafana: 172.20.10.70
            #minecraft-server: 172.20.10.80
          
volumes:
  mongodb_data:
  graylog_datanode:
  graylog_data:
  graylog_journal:
